services:
  dashboard:
    image: hoocken/dashboard:latest
    container_name: dashboard-container
    restart: always
    ports:
      - "3000:3000"
    
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /etc/ssl:/etc/nginx/ssl:ro
  #   restart: always 
  # backend:
  #   build:
  #     target: backend-dev
  #   ports:
  #     - "5050:5050"